export const AUDIT_ACTIONS = {
  CREATE_PATIENT: "CREATE_PATIENT",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  DELETE_PATIENT: "DELETE_PATIENT",
  CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
  UPDATE_APPOINTMENT_STATUS: "UPDATE_APPOINTMENT_STATUS",
  CREATE_PRESCRIPTION: "CREATE_PRESCRIPTION",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT"
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
